# Generated by Django 6.0.6 on 2026-06-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ongs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('objetivo', models.TextField()),
                ('publico_alvo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('carga_horaria', models.PositiveIntegerField(help_text='Carga horária total em horas')),
                ('vagas_turmas', models.PositiveIntegerField(default=1, help_text='Quantidade de turmas aceitas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='ongs.ong')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'projetos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
