# Generated by Django 6.0.6 on 2026-06-12 20:51

import django.db.models.deletion
import ongs.models.ong
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[ongs.models.ong.validar_cnpj])),
                ('razao_social', models.CharField(max_length=255)),
                ('causa_social', models.CharField(choices=[('educacao', 'Educação'), ('saude', 'Saúde'), ('meio_ambiente', 'Meio Ambiente'), ('direitos_humanos', 'Direitos Humanos'), ('assistencia_social', 'Assistência Social'), ('cultura', 'Cultura e Arte'), ('esporte', 'Esporte'), ('tecnologia', 'Tecnologia e Inovação')], max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ongs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ONG',
                'verbose_name_plural': 'ONGs',
                'db_table': 'ongs',
            },
        ),
    ]
