# Generated by Django 6.0.6 on 2026-06-14 18:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudantes', '0001_initial'),
        ('ongs', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='avaliacao_media',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Média das avaliações recebidas (0 a 10)', max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='AvaliacaoOng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, help_text='Nota de 0 a 10', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.TextField(blank=True, default='')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_ongs', to='estudantes.estudante')),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='ongs.ong')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_ong', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Avaliação de ONG',
                'verbose_name_plural': 'Avaliações de ONGs',
                'db_table': 'avaliacoes_ongs',
                'ordering': ['-data_avaliacao'],
                'unique_together': {('estudante', 'projeto')},
            },
        ),
    ]
