# Generated by Django 6.0.6 on 2026-06-14 18:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudantes', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.PositiveIntegerField(help_text='Total de horas cumpridas no projeto')),
                ('codigo_verificacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='estudantes.estudante')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'certificados',
                'ordering': ['-data_emissao'],
                'unique_together': {('estudante', 'projeto')},
            },
        ),
    ]
