# Generated by Django 6.0.6 on 2026-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('pratica', 'Prática'), ('teorica', 'Teórica'), ('workshop', 'Workshop'), ('pesquisa', 'Pesquisa'), ('extensao', 'Extensão')], max_length=20)),
                ('carga_horaria', models.PositiveIntegerField(help_text='Carga horária da atividade em horas')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('vagas', models.PositiveIntegerField(default=1, help_text='Quantidade de turmas aceitas nesta atividade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'atividades',
                'ordering': ['data_inicio'],
            },
        ),
    ]
