# Generated by Django 6.0.6 on 2026-06-12 21:58

import django.db.models.deletion
import professores.models.professores
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Universidade',
                'verbose_name_plural': 'Universidades',
                'db_table': 'universidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[professores.models.professores.validar_cpf])),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('lattes', models.URLField(blank=True, default='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to=settings.AUTH_USER_MODEL)),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professores', to='professores.universidade')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'professores',
            },
        ),
    ]
