# Generated by Django 6.0.6 on 2026-06-14 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudantes', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pontos', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('prata', 'Prata'), ('ouro', 'Ouro'), ('platina', 'Platina'), ('esmeralda', 'Esmeralda'), ('diamante', 'Diamante'), ('mestre', 'Mestre'), ('grao_mestre', 'Grão-Mestre'), ('desafiante', 'Desafiante')], default='bronze', max_length=20)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('estudante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='estudantes.estudante')),
            ],
            options={
                'verbose_name': 'Ranking do Estudante',
                'verbose_name_plural': 'Ranking dos Estudantes',
                'db_table': 'ranking_estudantes',
                'ordering': ['-total_pontos'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='estudantes.estudante')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Histórico do Estudante',
                'verbose_name_plural': 'Históricos dos Estudantes',
                'db_table': 'historico_estudantes',
                'ordering': ['-data_registro'],
                'unique_together': {('estudante', 'projeto')},
            },
        ),
    ]
