# Generated by Django 6.0.6 on 2026-06-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('voluntario_independente', 'Voluntário Independente'), ('estudante', 'Estudante'), ('professor', 'Professor'), ('ong', 'ONG'), ('administrador', 'Administrador')], default='estudante', max_length=30),
        ),
    ]
