# Generated by Django 6.0.6 on 2026-06-13 03:35

import django.db.models.deletion
import estudantes.models.estudantes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
        ('turmas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[estudantes.models.estudantes.validar_cpf])),
                ('data_nascimento', models.DateField()),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('curso', models.CharField(max_length=255)),
                ('periodo_curso', models.PositiveSmallIntegerField(help_text='Período atual do curso (ex: 5)')),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('lattes', models.URLField(blank=True, default='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudantes', to='professores.universidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
                'db_table': 'estudantes',
            },
        ),
        migrations.CreateModel(
            name='EstudanteTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pre_aprovado', 'Pré Aprovado'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pre_aprovado', max_length=20)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_inscricoes', to='estudantes.estudante')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Inscrição em Turma',
                'verbose_name_plural': 'Inscrições em Turmas',
                'db_table': 'estudantes_turmas',
                'unique_together': {('estudante', 'turma')},
            },
        ),
    ]
