# Generated by Django 6.0.6 on 2026-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('justificativa', models.TextField(blank=True, default='', help_text='Motivação do professor para participar')),
                ('feedback_ong', models.TextField(blank=True, default='', help_text='Resposta da ONG ao aceitar ou recusar')),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aplicação',
                'verbose_name_plural': 'Aplicações',
                'db_table': 'aplicacoes',
                'ordering': ['-data_aplicacao'],
            },
        ),
    ]
