# Generated by Django 6.0.6 on 2026-06-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicacoes', '0001_initial'),
        ('atividades', '0001_initial'),
        ('professores', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacao',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='atividades.atividade'),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='professores.professor'),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='turmas.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='aplicacao',
            unique_together={('professor', 'turma', 'atividade')},
        ),
    ]
