# Generated by Django 6.0.6 on 2026-06-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacoes', '0002_initial'),
        ('estudantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacao',
            name='estudantes_rejeitados',
            field=models.ManyToManyField(blank=True, related_name='aplicacoes_rejeitadas', to='estudantes.estudante'),
        ),
    ]
