# Generated by Django 6.0.6 on 2026-06-13 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('periodo', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], max_length=20)),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20)),
                ('semestre', models.CharField(help_text='Ex: 2025.1', max_length=10)),
                ('vagas', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='professores.universidade')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turmas',
            },
        ),
        migrations.CreateModel(
            name='TurmaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vinculo', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_professor', to='professores.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_professor', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Turma do Professor',
                'verbose_name_plural': 'Turmas dos Professores',
                'db_table': 'turmas_professor',
                'unique_together': {('professor', 'turma')},
            },
        ),
    ]
