# Generated by Django 6.0.6 on 2026-06-14 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudantes', '0001_initial'),
        ('ongs', '0001_initial'),
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Liderança', 'Liderança'), ('Trabalho em Equipe', 'Trabalho em Equipe'), ('Comunicação', 'Comunicação'), ('Organização', 'Organização'), ('Proatividade', 'Proatividade'), ('Impacto Social', 'Impacto Social'), ('Ensino e Capacitação', 'Ensino e Capacitação'), ('Inovação', 'Inovação')], max_length=50)),
                ('nivel', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], default='I', max_length=10)),
                ('descricao', models.TextField()),
                ('justificativa', models.TextField()),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('emissor_ong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_emitidas', to='ongs.ong')),
                ('emissor_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_emitidas', to='professores.professor')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='estudantes.estudante')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'badges',
            },
        ),
    ]
